version: '3.8'

volumes:
  ud_postgres_volume:
    name: ud_postgres_volume
  ud_redis_volume:
    name: ud_redis_volume
  ud_backend_volume:
    name: ud_backend_volume

networks:
  server_network:
    name: server_network

services:
  ud_nats:
    image: nats:alpine3.18
    hostname: ud_nats
    container_name: ud_nats
    restart: on-failure
    networks:
      - server_network
    expose:
      - 4222
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  ud_redis:
    image: redis:6.2-alpine
    hostname: ud_redis
    container_name: ud_redis
    restart: always
    command: /bin/sh -c "redis-server --loglevel warning --requirepass $${REDIS_PASSWORD} --appendonly yes"
    expose:
      - 6379
    env_file:
      - .redis-env
    volumes: 
      - ud_redis_volume:/data
    networks:
      - server_network

  ud_postgres:
    image: postgres:15.3-alpine
    hostname: ud_postgres
    container_name: ud_postgres
    restart: always
    expose:
      - 5432
    env_file:
      - .postgres-env
    volumes: 
      - ud_postgres_volume:/var/lib/postgresql/data
    networks:
      - server_network

  ud_backend:
    build: .
    image: ud_backend
    hostname: ud_backend
    container_name: ud_backend
    restart: always
    env_file:
      - .env
    volumes:
      - ud_backend_volume:/src/data
    ports:
      - 5555:5555
    networks:
      - server_network
    depends_on:
      - ud_redis
      - ud_postgres
      - ud_nats
    links:
      - ud_redis
      - ud_postgres
      - ud_nats
